api-test:
  name: Run postman collection
  needs: deploy-dev
  runs-on: ubuntu-latest

  steps:
    - name: Check out repo
      uses: actions/checkout@v4

    # - name: Setup NodeJS
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: "18.17.0"

    - name: Install newman
      run: |
        npm install -g newman newman-reporter-htmlextra

    - name: Run Postman Collection
      working-directory: .
      run: |
        newman run ./tests/ContactList1.json \
          --reporters cli,htmlextra \
          --env-var "baseUrl=${{ env.BASEURL }}" \
          --env-var "token=${{ secrets.TOKEN }}"

    - name: Upload Newman Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: postman-report
        path: newman
